alphalens/tests/test_utils.py, alphalens/utils.py
current implementation calculates daily returns as forward returns divided
by number of days:
daily_returns = fwd_ret / days
This patch calculate the daily returns as the value the returns would have
had every single day for 'forward' days if they had grown at a steady rate
that is:
daily_returns = (fwd_ret+1)**(1./days) - 1
=> BUG: wrong forward daily returns

alphalens/performance.py, alphalens/tears.py
The forward returns used in the variour retuns related plots are converted
to returns relative to mean (demeaned). it implies a long short portfolio
and that is not always the case. This commit make the demeaning optional
see #72
=> Making forward returns "demeaning" optional

alphalens/performance.py, alphalens/plotting.py, alphalens/tears.py
Call utils.common_start_returns just once as it is very computing
intensive.
Split the calculation of average cumulative returns from the plotting code
so that it's possible to reuse the same calculated average returns in the two
subsequent calls to plot_quantile_average_cumulative_return
=> Average cumulative returns by quantile: performance improvement

alphalens/performance.py, alphalens/tears.py
Issue #88 
As alphalens is data frequency agnostic, the aggregation by day performed
when calculating quantile mean returns doesn't make sense all the time. It
could produce better plots for some scenarios, depending on data
frequency and data time span, but not for all the possible data given in
input to alphalens.
I am suggesting to remove the aggregation by day
=> Avoid grouping by day when calculating quantile mean returns

alphalens/performance.py, alphalens/plotting.py, alphalens/tears.py, alphalens/tests/test_performance.py
Issue #64 
Also, this patch calculates quantiles turnover only once (currently is done 2 times: one inside plot.summary_stats and one inside plot.plot_top_bottom_quantile_turnover)
When turnover_for_all_periods is False, only 1 period turnover/autocorrelation is computed and plotted (regardless of what periods are passed in create_factor_tear_sheet).
=> Avoid period `1` persistence when new iterable is passed to create_factor_tear_sheet

alphalens/plotting.py
issue #99 
Affected plots:
- "Forward Return Information Coefficient (IC)"
- "Top Minus Bottom Quantile Mean Return"
Get the maximum Y axis range among all the plots and subsequently set
that as Y range for all the plots, so that you'd be able to visually
compare between multiple graphs. If the axes are different that becomes
much harder
=> Avoid hard coding Y axis range in plots

alphalens/performance.py, alphalens/tests/test_performance.py
When group information is provided to alphalens a group neutral cumulative returns plot is now displayed
=> Added sector neutral (actually group neutral) cumulative returns plot

alphalens/plotting.py
let `a` to be the output of the recursive call, and the replace the corresponding element in list `ax` with it, so that `a.get_ylim()` have the right method :
```python
for (i, a), (name, fr_column) in zip(enumerate(ax), mean_returns_spread.iteritems()):
stdn = None if std_err is None else std_err[name]
a = plot_mean_quantile_returns_spread_time_series(fr_column,
std_err=stdn,
ax=a)
ax[i] = a
curr_ymin, curr_ymax = a.get_ylim()
```
=> Fix issue #116 plot_mean_quantile_returns_spread_time_series seems failed with dataframe input

alphalens/tears.py
Mean Return and Average Cumulative Returns plots are now side by side to make the most of them, as the former is a detailed view of the latter at specific periods. Average Cumulative Returns plot is still optional.
=> Rearranged Group Specific Breakdown plots

alphalens/performance.py, alphalens/tests/test_performance.py, alphalens/tests/test_utils.py, alphalens/utils.py
demeaning option returns wrong values if the factor asset universe
varies from date to date. The tests don't cover this scenario, so
this patch fix the issue and add a test case too.
=> BUG: demeaning in average_cumulative_return_by_quantile

alphalens/performance.py, alphalens/tears.py, alphalens/tests/test_performance.py
I played a bit with the quantiles/bins tear sheet options and I found few bugs when I used a custom (non-uniform) quantiles/bins and when I selectively excluded certain quantiles/bins
=> bug fixes: using custom quantiles/bins might raise an exception

alphalens/plotting.py, alphalens/tears.py
Switched to 'darkgrid' axes style to improve readability, issue #124 
Also this fix another issue. The plotting.context function tries to set 'axes.facecolor' and 'figure.facecolor' properties using seaborn.plotting_context(), but that cannot work. seaborn.plotting_context() is intended to control the scale of plot elements while seaborn.axes_style() fucntion should be used for the style. So a combination of the two is required to have full control of the plotting properties. See http://seaborn.pydata.org/tutorial/aesthetics.html
=> Fix issue 124

.gitignore, alphalens/examples/.gitattributes
Mark notebook files as binary.
This prevents the embedded images in .ipynb files from destroying commands like `git grep` and `git diff`.
Also added a bunch of files to `.gitignore`.
=> Mark notebooks binary

alphalens/tears.py
When custom ranges are provided to quantiles/bins arguments then factor_data['factor_quantile'] contains float instead of integers, that in turn led to crashes
=> BUG: create_event_returns_tear_sheet crashes

alphalens/plotting.py
plot_cumulative_returns_by_quantile generates the following error when  quantiles=1
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/luca/.local/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
305                 pass
306             else:
--> 307                 return printer(obj)
308             # Finally look for special method names
309             method = get_real_method(obj, self.print_method)
/home/luca/.local/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
238 
239     if 'png' in formats:
--> 240         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
241     if 'retina' in formats …
```
=> BUG: plot_cumulative_returns_by_quantile crashes with quantiles=1

alphalens/tears.py
For example the following doesn't work:
```
with alphalens.plotting.plotting_context(style='whitegrid'), alphalens.plotting.axes_style():
alphalens.tears.create_full_tear_sheet(...,  set_context=False)
```
The problem is that each tear sheet function have a decorator, so we need to disable it when calling a tear sheet function from another one.
=> BUG: create_full_tear_sheet doesn't allow to set custom plotting_context/axes_style

alphalens/tears.py
In response to Issue #154, I modified the Returns Analysis table so that the "Mean Period Wise Return Top (Bottom) Quantile" rows displayed daily (one-period) returns, so that it is consistent with the "Mean Period Wise Spread" row.
=> Daily compound returns analysis

alphalens/tears.py, alphalens/utils.py
Correct the formula/function used to convert the standard error in the tear sheet to a one-period standard error. This is done by creating a new function in the utils module.
Issue #155
=> Fix std se conversion

README.rst
@twiecki  As agreed [here](https://github.com/quantopian/alphalens/pull/198) the preferred way to install Alphalens is now from pypi instead of gitub
=> DOC: updated installation instruction

alphalens/tests/test_tears.py, alphalens/utils.py
Dropping factor data without warning the user can incur in wrong results
interpretation. For this reason utils.get_clean_factor_and_forward_returns
has now a new parameter 'max_loss' that controls the maximum percentage of
factor data that can be dropped due to being flawed itself (e.g. NaNs),
not having provided enough price data to compute forward returns for all
factor values, or due to binning errors.
Also, small errors in the binning phase (utils.quantize_factor) caused by
sporadic flawed data don't raise exceptions anymore if the incurred data
loss is less than 'max_loss'
=> Make input preparation more robust and less annoying

alphalens/tests/test_tears.py, alphalens/utils.py
Don't be too strict with max_loss default value, that would be frustrating. So print the amount of dropped factor data even when the limit is not reached, so that the user is aware of what happened. 
Also the code is nicer now, the Exceptions that are suppressed by utils.quantize_factor can be now seen setting max_loss=0 so that troubleshooting potential issues is still possible.
=> max_loss increased to 25% by default

alphalens/performance.py, alphalens/tears.py, alphalens/tests/test_performance.py, alphalens/tests/test_tears.py, alphalens/utils.py
I am working on a sector neutral factor and I discovered that Alphalens analysis on a group neutral factor is currently limited. With group neutral factor I mean a factor intended to rank stocks across the same group, so that it makes sense to compare performance of top vs bottom stocks in the same group but it doesn't make sense to compare performance of a stock in one group with performance of another group.
The main shortcoming is the return analysis: as there is no way to demean the returns by group,  the statistics shown are of little use. Also when the plots are broken down by group, the results are not useful either as there are 2 bugs:
- API documentation claims that perf.mean_return_by_quantile was performing is performing the demeaning at group level when splitting the plots by …
=> Added support for group neutral factor analysis

alphalens/plotting.py, alphalens/utils.py
In response to issue #208 , this modifies and renames risk-adjusted IC calculation. I also moved this "Risk-Adjusted IC" to immediately follow the "IC Mean" and "IC Std." fields. This seems to be more logical especially since the "t-stat (IC)" field immediately follows, which I believe is simply the risk-adjusted IC times the square root of the number of periods.
=> Update IC Risk Adjusted Ratio Calculation

alphalens/performance.py, alphalens/tears.py, alphalens/tests/test_performance.py, alphalens/tests/test_tears.py
This reverts commit [2eed75589acf32cfcf87d93f86c9a55bf85cc1d8](https://github.com/quantopian/alphalens/commit/2eed75589acf32cfcf87d93f86c9a55bf85cc1d8).
The original commit was a oversight (actually a mistake :). As the flag was used to perform returns demeaning at group level before computing the IC between factor values and returns, the idea behind the commit was that subtracting a constant (the mean value) from the returns didn't affect the IC computation (IC is Spearman's rank correlation coefficient),
Unfortunately, as the IC is computed both on the full factor and by group, the flag is actually needed. Even though it doesn't change the IC at group level it is still relevant when computing IC for the full factor as we are indeed removing different values from different stocks (the …
=> Revert "Removed group_adjust/group_neutral flags from information analysis API"

alphalens/tears.py, alphalens/tests/test_tears.py
From matplotlib documentation:
The memory required for a Figure is not completely released until the figure is explicitly closed with close(). Deleting all references to the figure, and/or using the window manager to kill the window in which the figure appears on the screen, is not enough, because pyplot maintains internal references until close() is called.
=> BUG: Figures are not closed causing memory leak

alphalens/tears.py
Added plt.show() in the tears.* functions the same as pyfolio does so that Figures are properly displayed before being closed even without  "%matplotlib inline"
=> BUG: make sure Figures are displayed even without "%matplotlib inline"

alphalens/plotting.py
Forgot to add default palette change
=> ENH: Finish colorblindness update

alphalens/plotting.py, alphalens/tears.py, alphalens/tests/test_multi_factor.py
Simplified plotting.plot_multi_factor_quantile_returns and bused GridFigure class in tears API to follow other alphalens tears functions.
=> STY: Modify grid setup to follow other tears functions

alphalens/plotting.py, alphalens/utils.py
- ENH: use same quantiles colours in different plots 
Cumumlative Returns by Quantile  plot uses a different colour scheme for quantiles than Average Cumulative Returns by Quantile plot
- ENH: improve error message if prices and signals do not match
Issue #282
=> 2 small fixes

alphalens/performance.py, alphalens/utils.py
If 'groupby' data contains too many or missing values (grouby index is not the same as the factor index) then 'utils.get_clean_factor' and 'utils.get_clean_factor_and_forward_return' crash with meaningless error messages.
+ improved docstring for 'price' argument
=> BUG: get_clean_factor crashes with malformed 'groupby' data 

alphalens/plotting.py
This commit makes the positive IC blue and negative IC red
This is a regression introduced when improved the color scheme for colorblindness
=> BUG: monthly IC heatmap use red for positive IC

alphalens/performance.py, alphalens/tests/test_performance.py, alphalens/tests/test_utils.py, alphalens/utils.py
I noticed a performance regression after the last Alphalens update on Quantopian.
The slowness comes from utils.diff_custom_calendar_timedeltas, have a look at the profiler output.
Profiler output, pre-patch:
```
309336931 function calls (304638500 primitive calls) in 371.387 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000  371.404  371.404 tears.py:81(call_w_context)
4/1    0.000    0.000  371.404  371.404 plotting.py:38(call_w_context)
1    0.000    0.000  371.401  371.401 tears.py:553(create_full_tear_sheet)
1    0.000    0.000  352.342  352.342 tears.py:137(call_w_context)
1    0.000    0.000  352.342  352.342 tears.py:285(create_returns_tear_sheet)
12    3.431    0.286  342.883   28.574 …
```
=> PERF: computation of cumulative returns is very slow

alphalens/utils.py
Since Alphalens is not aware of the public holidays the computation of the periods goes wrong in certain scenarios. See issue #292
=> BUG: compute_forward_returns fails detecting the correct period length

alphalens/tears.py
Added option to display rate of return or simple return. Depending on the event we are analyzing it might
be more appropriate to use rate of return vs simple return
=> ENH: added rate of return option in 'create_event_study_tear_sheet'

alphalens/utils.py
In tests using pandas version 20.3, there was an error
`TypeError: Iterator operand 0 dtype could not be cast from
dtype('<M8[us]') to dtype('<M8[D]') according to the rule 'safe'`
Resolves Issue Discovered in #313
=> BUG: Fix date conversion in newer versions of pandas

alphalens/performance.py
Compute mean return by date. If by_date flag is false, then compute
and return the average of the daily mean returns (and also the
standard error of these daily mean returns).
Resolves: Issue #309
=> BUG: Calculate mean returns by date before mean return by quantile

alphalens/utils.py
By computing directly from prices rather than using `pct_change()`.
=> ENH Speed up fwdret computation

alphalens/performance.py, alphalens/plotting.py, alphalens/tears.py, alphalens/tests/test_performance.py
Added `freq` argument to `plot.plot_cumulative_returns` and `plot.plot_cumulative_returns_by_quantile`, which allow to avoid settings the index frequency inside `perf.to_weights` and `perf.factor_returns` (which in turn causes pandas  0.23.4 to crash, see #319 )
Also this closes #319
=> MAINT: code refactoring to make it compatible with pandas 0.23.4

alphalens/tests/test_utils.py, alphalens/utils.py
A straightforward bug fix: just added a check on boundaries when accessing the index
This closes #331
=> BUG: utils.compute_forward_returns can raise out of bounds exception

alphalens/tears.py
Added code to address issue #336. 
link: https://github.com/quantopian/alphalens/issues/336
=> Addressing issue #336

alphalens/utils.py
fix for https://github.com/quantopian/alphalens/issues/359 which is blocking `get_clean_factor_and_forward_returns` for pandas>=1.0
=> use MultiIndex.set_names for pandas 1.0
