- alphalens/plotting.py
- alphalens/tears.py
- alphalens/utils.py
issue #70, for your evaluation
> Added average cumulative quantile return plot

- alphalens/tears.py
There was a lot of copy and paste of code for dealing with grid plots and
I condensed all the boilerplate in a helper class
> Simplified grid plot code

- alphalens/plotting.py
- alphalens/tears.py
Cumulative Return by Quantile plot for each period and
Factor Weighted Cumulative Return plot for each period
Issue #66 and #65
> Plot Cumulative Return for each period

- alphalens/plotting.py
- alphalens/tears.py
ENH: added "Average Cumulative Returns by Quantile" plot by group
> ENH: added "Average Cumulative Returns by Quantile" plot by group

- alphalens/tears.py
- alphalens/utils.py
and moved the function inside utils
> Renamed compound_returns to rate_of_return (more appropriate)

- alphalens/plotting.py
one line bug fix for issue #115
> BUG: fix issue #115

- alphalens/plotting.py
> fix to previous commit

- alphalens/utils.py
I ran some benchmarks and it was too slow.
> Improved performance of utils.common_start_returns

- alphalens/utils.py
> Removed deprecated api .ix[...] (pandas 0.20.0)

- alphalens/plotting.py
Updated function documentation to reflect how the functions actually work
> plotting_context and axes_style: updated doc string

- alphalens/plotting.py
> BUG: make plots more robust to nans

- alphalens/performance.py
This commit correctly identifies the independent and dependent
variable for the regression.
Issue #156
> Correct factor_alpha_beta() doc string

- alphalens/utils.py
> Better error message for not enough quantiles for factor values

- alphalens/performance.py
- alphalens/tears.py
It is not very clear the intent of 'long_short' option, so I added a little explanation.
> Improve 'long_short' option documentation

- alphalens/utils.py
> Improved explanation of 'prices' in get_clean_factor_and_forward_returns

- .travis.yml
As recommended by @richafrank in #179
> only test master branch

- alphalens/plotting.py
> BUG: ValueError: Invalid RGBA argument: 0.0`

- alphalens/utils.py
An example is worth thousands words
> Improved documentation of 'Prices' argument in get_clean_factor_and_forward_returns

- alphalens/plotting.py
related to #187
Explained how to interpret the cumulative return for N forward period in
performace.plot_cumulative_returns and performance.plot_cumulative_returns_by_quantile
> Updated documentation of performace.plot_cumulative_returns

- alphalens/plotting.py
- alphalens/utils.py
> BUG: cumulative return plots not correct

- alphalens/utils.py
Better described the possible solutions
> Improved help message for 'Bin edges must be unique' error

- alphalens/plotting.py
- setup.py
I changed the instances of `rolling_mean` to use the new API. The instances of `rolling_apply` that are used elsewhere should be updated on top of these.
> Changed pd.rolling_mean() to use the new *.rolling().mean() API

- alphalens/utils.py
> Removed deprecated DataFrame.rolling_apply

- alphalens/utils.py
Added missing backward compatibility for get_clean_factor_and_forward_returns
I forgot that 'by_group' argument was renamed 'binning_by_group'
> Added backward compatibility for get_clean_factor_and_forward_returns

- alphalens/examples/event_study.ipynb
- alphalens/utils.py
Made Little changes due to the recent API change and also improved price DataFrame explanation
> Updated example NBs 

- alphalens/utils.py
The user message is intended to give useful information but the current
message create FUD. This commit rephrase the message and add an "OK!"
to make the users comfortable.
Also, max_loss increased to 35%
> DOC: improve user message regarding data loss in get_clean_factor_and_forward_returns

- alphalens/performance.py
- alphalens/plotting.py
- alphalens/tests/test_performance.py
- alphalens/tests/test_utils.py
- alphalens/utils.py
Some corner cases were not properly handled by cumulative_returns function + added some more tests
factor_rank_autocorrelation and quantile_turnover have now better defaults
> MAINT: additional improvements to recently merged PR

- alphalens/utils.py
Sorry for those unexpected commits but I have been doing extensive testing and I found some regressions introduced in the "Pyfolio integration feature" PR
> MAINT: some additional small fixes

- alphalens/performance.py
- alphalens/plotting.py
- alphalens/tests/test_tears.py
More on small bug fixes,refactoring, tests and example NBs.
> Small refinements

- .travis.yml
Test pandas 0.18.1, 0.19.2, 0.20.3
Also test python 3.6 and not 3.4
> TST: test multiple pandas versions

- alphalens/performance.py
- alphalens/tears.py
- alphalens/tests/test_performance.py
- alphalens/utils.py
small changes required to finish up pyfolio integration
> EHN: allow factor returns to be equal weighted

- alphalens/tears.py
First print information and then plot
> STY: restored old behavior in create_summary_tear_sheet

- alphalens/tears.py
Sometimes the user just want the event study style return plot without the additional sub-plots that show the standard deviation bars. Added an option to allow the sub-plots to be optional.
> API: standard deviation bars optional in create_event_returns_tear_sheet

- alphalens/utils.py
Cleaned up the code that deals with business days calendar. The code now infers the trading calendar from prices and factor information
> MAINT: refactored utils.compute_forward_returns

- alphalens/plotting.py
- alphalens/tears.py
Update plotting style to be consistent with other alphalens tears.
1. Use coolwarm colormap
2. Use plotting.customize to decorate tears function.
> Plotting style

- alphalens/tests/test_utils.py
- alphalens/utils.py
since we are refactoring  `utils.test_get_clean_factor_and_forward_returns `it is good to have non-regression tests before applying any change
> TST: added tests for utils.test_get_clean_factor_and_forward_returns

- README.rst
I also tweaked the wording of the existing installation instructions, hopefully it makes sense.
> Add conda installation instructions to the readme

- alphalens/tests/test_utils.py
- alphalens/utils.py
For issue #253 
refactor compute_forward_returns
add get_clean_factor API
refactor get_clean_factor_and_forward_returns as compose of compute_forward_returns and get_clean_factor
> API: run Alphalens with returns instead of prices (utils.get_clean_factor)

- alphalens/performance.py
When passing factor data computed at frequency higher than 1 day the resulting output is not properly displayed by pyfolio
> BUG: create_pyfolio_input doesn't work with frequency higher that 1 day

- alphalens/tears.py
Added option to control the number of bars to use in the event distribution plot
> ENH: added n_bars option in 'create_event_study_tear_sheet'

- alphalens/performance.py
> BUG: compute_mean_return_spread returns error if no std_err argument

- alphalens/tears.py
- alphalens/utils.py
Issue #268 
The PR is ready, but let's wait until we are sure we don't need the backward compatibility layer anymore before merging this.
> MAINT: clean up backward compat API (DO NOT MERGE)

- alphalens/performance.py
Assuming we run flake8 over this, I will be sad if this fails the style check
> DOC: Small typo in docstring

- alphalens/utils.py
For decent sized inputs (~1M+ asset/day values in `prices` and ~1M asset/day values in `factor`), we were spending enormous amounts of time doing index alignment when combining things with different indices.
This change makes it so that we are never combining two dataseries with different indices.
The returned dataframe from `compute_forward_returns` used to contain date/asset pairs that didn't exist in `factor`, which made it very slow to add the `factor` series into the dataframe in `get_clean_factor`.  Now, `compute_forward_returns` only returns date/asset pairs that exist in `factor`.
Locally, for a `prices` df with ~4400 unique assets and 3500 days, and a `factor` series spanning 859 unique assets across 1308 days, `get_clean_factor_and_forward_returns` went from ~203 seconds to ~5 …
> ENH: Speed up `compute_forward_returns` and `get_clean_factor`.

- alphalens/tests/test_utils.py
- alphalens/utils.py
This makes a whole bunch of new calculations I'm doing much simpler.
> Add option to compute forward returns non-cumulatively

- .github/ISSUE_TEMPLATE.md
This should make it easier to receive and triage bug reports.
I based the issue template off of [PyMC3's](https://github.com/pymc-devs/pymc3/blob/master/.github/ISSUE_TEMPLATE.md).
> DOC: add GitHub issue template

- README.rst
@twiecki looking at the issues created on the project I could see that there are several aspects of Alphalens that are misunderstood from the users. This is because the full possibilities of the libraries are not completely covered in the existing tutorials. Since long time ago you asked me if I could add this tutorial to the project here is a PR. The only drawback is that it focuses  on Quantopian API, but at the same time this is useful to give a complete understanding of Alphalens. I'll let you decide if you like to add it to the project.
> Advanced tutorial on Alphalens (on Quantopian)
